### ISSUE TITLE
Server feature request: chat: Use FiveM/NUI chat

### ISSUE THREAD

**Issue by blattersturm** [adikanchukov/los-santos-v#7]
Currently, the `cfx-server-data` repository contains a `chat-theme-gtao` lookalike of the native Scaleform chat.

Would it be possible to use this on the actual server, potentially customizing it with any appearance changes required here?

**Comment by warxander** [comment]
I'm not using FiveM chat, because:
- I'm bad at HTML/CSS/JS stack, so I cannot control and fix it if I'll need it
- It looks _a bit_ like in-game chat
- It has issues like displaying two lines after first opening
- It has no `exports`, so I cannot even check if it's open for displaying another UI properly
